// <auto-generated />
using System;
using CRUD_Operations_PostGresSQl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRUD_Operations_PostGresSQl.Migrations
{
    [DbContext(typeof(CrudDbContext))]
    [Migration("20230731093401_LeadListTable")]
    partial class LeadListTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("CRUD_Operations_PostGresSQl.Models.Domain.LeadList", b =>
                {
                    b.Property<Guid>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LeadAssignedTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadCreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LeadCreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("LeadEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadLoanType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LeadMarkedForReview")
                        .HasColumnType("boolean");

                    b.Property<string>("LeadProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeadId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("CRUD_Operations_PostGresSQl.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
